version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      # Android the primary container
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Change Permissions
          command: sudo chmod +x gradlew
      - run:
            name: Build debug APK and release APK
            command: |
                  ./gradlew :app:assembleDebug
                  ./gradlew :app:assembleDebugAndroidTest
      - run:
           name: Store Google Service Account
           ommand: echo $GCLOUD_SERVICE_KEY
           command: echo $GCLOUD_SERVICE_KEY > ${HOME}/google-services.json
      - run:
            name: Authorize gcloud and set config defaults
            command: |
              sudo gcloud auth activate-service-account --key-file=app/keys.json
              sudo gcloud  config set project "emulator-5cbfd"
      - run:
          name: Test with Firebase Test Lab
          command: >
            sudo gcloud firebase test android run --type instrumentation --app app/build/outputs/apk/debug/app-debug.apk --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
      - run:
          name: Install gsutil dependency and copy test results data
          command: |
            sudo pip install -U crcmod
            sudo gsutil -m cp -r -U `sudo gsutil ls gs://staging.emulator-5cbfd.appspot.com/Test_Results | tail -1` ${CIRCLE_ARTIFACTS}/ | true
      - run:
          name: Run EspressoTests
          command: gcloud firebase test android run --type instrumentation --app app/build/outputs/apk/debug/app-debug.apk --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk --device model=Pixel2,version=27,locale=en,orientation=portrait
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
          
          
